name: Test UV Python version

on:
  pull_request:
    paths-ignore:
      - "manifests/**"

jobs:
  test-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        if: ${{ fromJson(inputs.github).event_name != 'pull_request_target' }}
        with:
          lfs: ${{ contains(inputs.target, 'codeserver') }}
      # we need to checkout the pr branch, not pr target (the default for pull_request_target)
      # user access check is done in calling workflow
      - uses: actions/checkout@v6
        if: ${{ fromJson(inputs.github).event_name == 'pull_request_target' }}
        with:
          ref: "refs/pull/${{ fromJson(inputs.github).event.number }}/merge"
          lfs: ${{ contains(inputs.target, 'codeserver') }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"

      - name: Check uv is installed correctly
        run: uv version

      - name: Show UV_PYTHON and Python info
        run: |
          which python3
          python3 --version
